### ISSUE TITLE
ToDo (Selecionar questões)

### ISSUE THREAD

**Issue by wellington36** [wellington36/intermediate-statistics-problems#2]
- [ ] Adicionar Lista 7 do curso do max
- [ ] Verificar provas antigas do curso do max
- [ ] Verificar provas antigas do curso do [Sivaraman Balakrishnan](https://www.stat.cmu.edu/~siva//~siva//)
- [ ] (Maybe) adicionar Lista 5 do curso do max

**Comment by wellington36** [comment]
Not used.
